options:
  url:
    description: The URL to use when providing links to the site.
    type: string
    default: http://my-ghost-blog.com
  host:
    description: Host to be passed to node's net.Server listen().
    type: string
    default: 0.0.0.0
  port:
    description: Port to be passed to node's net.Server listen().
    type: int
    default: 2368
